using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace GameSourceGeneration
{
    [Generator]
    public class EntityAspectInterfaceGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Collecte tous les structs qui implémentent IEntityAspect<...>
            IncrementalValuesProvider<int> arities = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => node is StructDeclarationSyntax { BaseList: not null },
                    transform: static (ctx, _) => GetAspectArity(ctx))
                .Where(static arity => arity > 0)
                .Collect()
                .SelectMany(static (arities, _) => arities.Distinct());

            context.RegisterSourceOutput(arities, static (ctx, arity) =>
            {
                string source = GenerateInterface(arity);
                ctx.AddSource($"IEntityAspect{arity}.g.cs", SourceText.From(source, Encoding.UTF8));
            });
        }

        private static int GetAspectArity(GeneratorSyntaxContext ctx)
        {
            var structDecl = (StructDeclarationSyntax)ctx.Node;
            if (structDecl.BaseList == null) return 0;

            foreach (BaseTypeSyntax baseType in structDecl.BaseList.Types)
            {
                // 1. Test SYNTAXIQUE d'abord (marche même si le type n'existe pas encore)
                if (baseType.Type is GenericNameSyntax generic &&
                    generic.Identifier.Text == "IEntityAspect")
                {
                    return generic.TypeArgumentList.Arguments.Count;
                }

                // 2. Test SÉMANTIQUE (si l'interface existe déjà dans une DLL par exemple)
                TypeInfo typeInfo = ctx.SemanticModel.GetTypeInfo(baseType.Type);
                if (typeInfo.Type is INamedTypeSymbol namedType)
                {
                    INamedTypeSymbol original = namedType.OriginalDefinition;
                    if (original.Name == "IEntityAspect")
                        return original.TypeParameters.Length;
                }
            }
            return 0;
        }

        private static string GenerateInterface(int arity)
        {
            var typeParams = Enumerable.Range(1, arity).Select(i => $"T{i}").ToList();
            string typeParamList = string.Join(", ", typeParams);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using ATCG.Battle.Entities.Components;");
            sb.AppendLine();
            sb.AppendLine("namespace ATCG.Battle.Entities");
            sb.AppendLine("{");
            sb.AppendLine($"    public interface IEntityAspect<{typeParamList}> : IEntityAspect");

            foreach (var t in typeParams)
                sb.AppendLine($"        where {t} : struct, IEntityComponent");

            sb.AppendLine("    {");
            sb.AppendLine("        ComponentMask IEntityAspect.ComponentMask => ComponentMask");

            for (int i = 0; i < typeParams.Count; i++)
            {
                string ending = i < typeParams.Count - 1 ? "" : ";";
                sb.AppendLine($"            .With<{typeParams[i]}>(){ ending}");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}