// SourceGenerators/ATCG.SourceGen/Generators/IteratableComponentGenerator.cs

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ATCG.SourceGen.Generators
{
    [Generator]
    public sealed class IteratableComponentGenerator : IIncrementalGenerator
    {
        // Both attributes are declared by hand in the consuming assembly, under this namespace.
        // GenerateIterator: any type (struct or class) implementing the marked interface.
        // GenerateComponentIterator: ECS components only — keeps the struct, IEntityComponent
        // constraint so Process<T>() stays usable with World.Query / EntityAddress.TryGetComponent.
        private const string AttributeFullName = "ATCG.Battle.Utilities.Iterations.GenerateIteratorAttribute";
        private const string ComponentAttributeFullName = "ATCG.Battle.Utilities.Iterations.GenerateComponentIteratorAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            RegisterFor(context, AttributeFullName, requireStruct: false);
            RegisterFor(context, ComponentAttributeFullName, requireStruct: true);
        }

        private static void RegisterFor(
            IncrementalGeneratorInitializationContext context,
            string attributeFullName,
            bool requireStruct)
        {
            var targetInterfaces = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    attributeFullName,
                    predicate: static (node, _) => node is InterfaceDeclarationSyntax,
                    transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol)
                .Collect();

            var combined = targetInterfaces.Combine(context.CompilationProvider);

            context.RegisterSourceOutput(combined, (spc, source) =>
            {
                var (interfaces, compilation) = source;

                foreach (var targetInterface in interfaces.Distinct(SymbolEqualityComparer.Default)
                             .Cast<INamedTypeSymbol>())
                {
                    Execute(targetInterface, compilation, spc, requireStruct);
                }
            });
        }

        private static void Execute(
            INamedTypeSymbol targetInterface,
            Compilation compilation,
            SourceProductionContext spc,
            bool requireStruct)
        {
            var implementors = FindImplementingTypes(targetInterface, compilation, requireStruct);

            string interfaceName = targetInterface.Name;                          // "IStatusComponent"
            string iteratorInterfaceName = interfaceName + "Iterator";            // "IStatusComponentIterator"
            string shortName = interfaceName.StartsWith("I") ? interfaceName.Substring(1) : interfaceName;
            string methodName = "Foreach" + shortName;                            // "ForeachStatusComponent"
            string extensionsClassName = shortName + "IteratorExtensions";        // "StatusComponentIteratorExtensions"
            string fqInterfaceName = targetInterface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            string containingNamespace = targetInterface.ContainingNamespace.IsGlobalNamespace
                ? null
                : targetInterface.ContainingNamespace.ToDisplayString();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable disable");
            sb.AppendLine();

            bool hasNamespace = containingNamespace != null;
            string indent = hasNamespace ? "    " : "";

            if (hasNamespace)
            {
                sb.AppendLine($"namespace {containingNamespace}");
                sb.AppendLine("{");
            }

            // Iterator interface is always generated (single source of truth: the marked interface).
            sb.AppendLine($"{indent}public interface {iteratorInterfaceName}");
            sb.AppendLine($"{indent}{{");
            string constraint = requireStruct ? $"struct, {fqInterfaceName}" : fqInterfaceName;
            sb.AppendLine($"{indent}    void Process<T>() where T : {constraint};");
            sb.AppendLine($"{indent}}}");
            sb.AppendLine();

            sb.AppendLine($"{indent}public static class {extensionsClassName}");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    public static void {methodName}(this {iteratorInterfaceName} iterator)");
            sb.AppendLine($"{indent}    {{");

            // One dispatch per concrete type that implements the marked interface.
            // Under GenerateComponentIterator, that set is struct-only (non-boxing);
            // under GenerateIterator, classes are included too (and box as usual for T).
            foreach (var impl in implementors)
            {
                string fqImpl = impl.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                sb.AppendLine($"{indent}        iterator.Process<{fqImpl}>();");
            }

            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}}}");

            if (hasNamespace)
                sb.AppendLine("}");

            spc.AddSource($"{iteratorInterfaceName}.g.cs", sb.ToString());
        }

        private static ImmutableArray<INamedTypeSymbol> FindImplementingTypes(
            INamedTypeSymbol targetInterface,
            Compilation compilation,
            bool requireStruct)
        {
            var seen = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
            var result = ImmutableArray.CreateBuilder<INamedTypeSymbol>();

            void VisitType(INamedTypeSymbol type)
            {
                // Non-abstract, non-generic types that implement the marked interface.
                // GenerateComponentIterator restricts this to structs (ECS component
                // storage is struct-only); GenerateIterator allows classes too.
                bool kindAllowed = requireStruct
                    ? type.TypeKind == TypeKind.Struct
                    : type.TypeKind == TypeKind.Struct || type.TypeKind == TypeKind.Class;

                if (kindAllowed
                    && !type.IsAbstract
                    && type.Arity == 0
                    && type.AllInterfaces.Contains(targetInterface, SymbolEqualityComparer.Default)
                    && seen.Add(type))
                {
                    result.Add(type);
                }

                // Recurse into nested types.
                foreach (var nested in type.GetTypeMembers())
                    VisitType(nested);
            }

            void VisitNamespace(INamespaceSymbol ns)
            {
                foreach (var member in ns.GetMembers())
                {
                    if (member is INamespaceSymbol childNs)
                        VisitNamespace(childNs);
                    else if (member is INamedTypeSymbol type)
                        VisitType(type);
                }
            }

            // Scan restricted to the current assembly: iteration happens within a single assembly.
            VisitNamespace(compilation.Assembly.GlobalNamespace);

            // Deterministic ordering to avoid spurious diffs between builds.
            result.Sort((a, b) => string.CompareOrdinal(
                a.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                b.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));

            return result.ToImmutable();
        }
    }
}