// SourceGenerators/ATCG.SourceGen/Generators/IteratableComponentGenerator.cs

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ATCG.SourceGen.Generators
{
    [Generator]
    public sealed class IteratableComponentGenerator : IIncrementalGenerator
    {
        // The attribute is declared by hand in the consuming assembly, under this namespace.
        private const string AttributeFullName = "ATCG.Battle.Entities.Iterations.IteratableComponentAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var targetInterfaces = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    AttributeFullName,
                    predicate: static (node, _) => node is InterfaceDeclarationSyntax,
                    transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol)
                .Collect();

            var combined = targetInterfaces.Combine(context.CompilationProvider);

            context.RegisterSourceOutput(combined, static (spc, source) =>
            {
                var (interfaces, compilation) = source;

                foreach (var targetInterface in interfaces.Distinct(SymbolEqualityComparer.Default)
                             .Cast<INamedTypeSymbol>())
                {
                    Execute(targetInterface, compilation, spc);
                }
            });
        }

        private static void Execute(
            INamedTypeSymbol targetInterface,
            Compilation compilation,
            SourceProductionContext spc)
        {
            var implementors = FindImplementingStructs(targetInterface, compilation);

            string interfaceName = targetInterface.Name;                          // "IStatusComponent"
            string iteratorInterfaceName = interfaceName + "Iterator";            // "IStatusComponentIterator"
            string shortName = interfaceName.StartsWith("I") ? interfaceName.Substring(1) : interfaceName;
            string methodName = "Foreach" + shortName;                            // "ForeachStatusComponent"
            string extensionsClassName = shortName + "IteratorExtensions";        // "StatusComponentIteratorExtensions"
            string fqInterfaceName = targetInterface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            string containingNamespace = targetInterface.ContainingNamespace.IsGlobalNamespace
                ? null
                : targetInterface.ContainingNamespace.ToDisplayString();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable disable");
            sb.AppendLine();

            bool hasNamespace = containingNamespace != null;
            string indent = hasNamespace ? "    " : "";

            if (hasNamespace)
            {
                sb.AppendLine($"namespace {containingNamespace}");
                sb.AppendLine("{");
            }

            // Iterator interface is always generated (single source of truth: the marked interface).
            sb.AppendLine($"{indent}public interface {iteratorInterfaceName}");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    void Process<T>() where T : struct, {fqInterfaceName};");
            sb.AppendLine($"{indent}}}");
            sb.AppendLine();

            sb.AppendLine($"{indent}public static class {extensionsClassName}");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    public static void {methodName}(this {iteratorInterfaceName} iterator)");
            sb.AppendLine($"{indent}    {{");

            // One non-boxing dispatch per concrete struct that implements the marked interface.
            foreach (var impl in implementors)
            {
                string fqImpl = impl.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                sb.AppendLine($"{indent}        iterator.Process<{fqImpl}>();");
            }

            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}}}");

            if (hasNamespace)
                sb.AppendLine("}");

            spc.AddSource($"{iteratorInterfaceName}.g.cs", sb.ToString());
        }

        private static ImmutableArray<INamedTypeSymbol> FindImplementingStructs(
            INamedTypeSymbol targetInterface,
            Compilation compilation)
        {
            var seen = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
            var result = ImmutableArray.CreateBuilder<INamedTypeSymbol>();

            void VisitType(INamedTypeSymbol type)
            {
                // Only non-abstract, non-generic structs that implement the marked interface.
                if (type.TypeKind == TypeKind.Struct
                    && !type.IsAbstract
                    && type.Arity == 0
                    && type.AllInterfaces.Contains(targetInterface, SymbolEqualityComparer.Default)
                    && seen.Add(type))
                {
                    result.Add(type);
                }

                // Recurse into nested types.
                foreach (var nested in type.GetTypeMembers())
                    VisitType(nested);
            }

            void VisitNamespace(INamespaceSymbol ns)
            {
                foreach (var member in ns.GetMembers())
                {
                    if (member is INamespaceSymbol childNs)
                        VisitNamespace(childNs);
                    else if (member is INamedTypeSymbol type)
                        VisitType(type);
                }
            }

            // Scan restricted to the current assembly: iteration happens within a single assembly.
            VisitNamespace(compilation.Assembly.GlobalNamespace);

            // Deterministic ordering to avoid spurious diffs between builds.
            result.Sort((a, b) => string.CompareOrdinal(
                a.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                b.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));

            return result.ToImmutable();
        }
    }
}