using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Helteix.Tools.DataMapping.SourceGen
{
    /// <summary>
    /// For every (partial) struct that implements a behaviour interface annotated
    /// with <c>[MappedBehaviour(typeof(SomeContainer&lt;,&gt;), typeof(ISomeBucket))]</c>,
    /// emits:
    /// <code>
    /// partial struct Foo : ISelfMapping&lt;FooData&gt;
    /// {
    ///     public void BuildAndRegister()
    ///         =&gt; DomainBucket&lt;ISomeBucket&gt;.Add(new SomeContainer&lt;FooData, Foo&gt;(this));
    /// }
    /// </code>
    /// Works for any domain (patterns, effects, …) because the wiring is read
    /// from the attribute on the interface, not hard-coded.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class SelfMappingGenerator : IIncrementalGenerator
    {
        private const string AttrMetadataName = "Helteix.Tools.DataMapping.MappedBehaviourAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var candidates = context.SyntaxProvider.CreateSyntaxProvider(
                    predicate: static (node, _) =>
                        node is StructDeclarationSyntax s &&
                        s.BaseList is not null &&
                        s.Modifiers.Any(m => m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword)),
                    transform: static (ctx, _) =>
                        ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as INamedTypeSymbol)
                .Where(static s => s is not null);

            var combined = context.CompilationProvider.Combine(candidates.Collect());

            context.RegisterSourceOutput(combined, static (spc, pair) =>
            {
                var (compilation, structs) = pair;
                var attr = compilation.GetTypeByMetadataName(AttrMetadataName);
                if (attr is null) return;

                foreach (var type in structs.Distinct(SymbolEqualityComparer.Default).Cast<INamedTypeSymbol>())
                {
                    if (TryBuild(type, attr, out var hint, out var source))
                        spc.AddSource(hint, source);
                }
            });
        }

        private static bool TryBuild(INamedTypeSymbol type, INamedTypeSymbol attrSymbol,
                                     out string hintName, out string source)
        {
            hintName = null;
            source = null;

            foreach (var iface in type.AllInterfaces)
            {
                var def = iface.OriginalDefinition;

                var mapped = def.GetAttributes().FirstOrDefault(a =>
                    SymbolEqualityComparer.Default.Equals(a.AttributeClass, attrSymbol));
                if (mapped is null) continue;
                if (iface.TypeArguments.Length != 1) continue;
                if (mapped.ConstructorArguments.Length != 2) continue;
                if (mapped.ConstructorArguments[0].Value is not INamedTypeSymbol containerOpen) continue;
                if (mapped.ConstructorArguments[1].Value is not INamedTypeSymbol bucket) continue;
                if (containerOpen.Arity != 2) continue;

                var dataType = (INamedTypeSymbol)iface.TypeArguments[0];

                string ns = type.ContainingNamespace.IsGlobalNamespace
                    ? null
                    : type.ContainingNamespace.ToDisplayString();

                string dataFq = dataType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                string selfFq = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                string bucketFq = bucket.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                // Container open generic → fully qualified name WITHOUT arity, then
                // re-close with <TData, TSelf>.
                string containerName = containerOpen.ConstructUnboundGenericType()
                    .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                // ConstructUnboundGenericType renders as Namespace.Container<,> ; strip the <,>.
                int lt = containerName.IndexOf('<');
                if (lt >= 0) containerName = containerName.Substring(0, lt);
                string containerClosed = $"{containerName}<{dataFq}, {selfFq}>";

                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine("#nullable enable");
                sb.AppendLine("using Helteix.Tools.DataMapping;");
                sb.AppendLine();
                bool hasNs = ns != null;
                if (hasNs)
                {
                    sb.Append("namespace ").AppendLine(ns);
                    sb.AppendLine("{");
                }

                string keyword = BuildKeyword(type); // e.g. "readonly partial struct"
                sb.Append("    ").Append(keyword).Append(' ').Append(type.Name)
                  .Append(" : ISelfMapping<").Append(dataFq).AppendLine(">");
                sb.AppendLine("    {");
                sb.AppendLine("        public void BuildAndRegister()");
                sb.Append("            => DomainBucket<").Append(bucketFq)
                  .Append(">.Add(new ").Append(containerClosed).AppendLine("(this));");
                sb.AppendLine("    }");
                if (hasNs) sb.AppendLine("}");

                string safe = selfFq.Replace("global::", "")
                                    .Replace('.', '_').Replace('<', '_').Replace('>', '_')
                                    .Replace(", ", "_").Replace(",", "_");
                hintName = $"{safe}.SelfMapping.g.cs";
                source = sb.ToString();
                return true;
            }
            return false;
        }

        private static string BuildKeyword(INamedTypeSymbol type)
        {
            // The generated partial must match the declared modifiers' shape.
            // struct is required; readonly is allowed on the partial too.
            return type.IsReadOnly ? "readonly partial struct" : "partial struct";
        }
    }
}