using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace GameSourceGeneration.Sources.Status
{
    /// <summary>
    /// Every non-abstract Status&lt;,&gt; / Status&lt;,,&gt; subclass must implement
    /// AddSignature(EntityAddress) with the same CRTP boilerplate:
    ///   protected sealed override void AddSignature(EntityAddress address)
    ///       => address.AddOrSetComponent&lt;StatusSignature&lt;TSelf&gt;&gt;();
    /// This generator emits that override for every partial class matching the shape,
    /// sealed so it can't be re-overridden further down an inheritance chain. Classes
    /// that already declare AddSignature by hand are left alone (no duplicate member).
    /// Non-partial matches get a diagnostic instead of silently doing nothing.
    /// </summary>
    [Generator]
    public sealed class StatusSignatureGenerator : IIncrementalGenerator
    {
        private const string StatusMetadataName2 = "Status`2";
        private const string StatusMetadataName3 = "Status`3";
        private const string StatusNamespace = "ATCG.Battle.CapacitySystem.Core.Status";
        private const string EntityAddressNamespace = "ATCG.Battle.Entities";

        private static readonly DiagnosticDescriptor NotPartial = new(
            id: "STA001",
            title: "Status subclass must be partial",
            messageFormat: "'{0}' derives from Status<> but is not declared partial, so AddSignature could not be generated. Add the 'partial' modifier or implement AddSignature by hand.",
            category: "ATCG.Status",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            IncrementalValuesProvider<StatusModel?> models = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                    transform: static (ctx, _) => BuildModel(ctx))
                .Where(static m => m != null);

            context.RegisterSourceOutput(models, static (spc, model) => Emit(spc, model!.Value));
        }

        private static StatusModel? BuildModel(GeneratorSyntaxContext ctx)
        {
            var classDecl = (ClassDeclarationSyntax)ctx.Node;

            if (ctx.SemanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol typeSymbol)
                return null;

            if (typeSymbol.IsAbstract)
                return null;

            if (!DerivesFromStatus(typeSymbol))
                return null;

            // Respect a hand-written override — don't generate a duplicate member.
            bool alreadyImplemented = typeSymbol.GetMembers("AddSignature")
                .OfType<IMethodSymbol>()
                .Any(m => SymbolEqualityComparer.Default.Equals(m.ContainingType, typeSymbol));

            if (alreadyImplemented)
                return null;

            bool isPartial = classDecl.Modifiers.Any(m => m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword));

            return new StatusModel(
                typeSymbol.ContainingNamespace.IsGlobalNamespace ? null : typeSymbol.ContainingNamespace.ToDisplayString(),
                typeSymbol.Name,
                isPartial,
                classDecl.Identifier.GetLocation());
        }

        // Walks the base type chain looking for Status<TData,TController> or
        // Status<TData,TComponent,TController> from ATCG.Battle.CapacitySystem.Core.Status.
        private static bool DerivesFromStatus(INamedTypeSymbol typeSymbol)
        {
            for (INamedTypeSymbol baseType = typeSymbol.BaseType; baseType != null; baseType = baseType.BaseType)
            {
                if ((baseType.MetadataName == StatusMetadataName2 || baseType.MetadataName == StatusMetadataName3)
                    && baseType.ContainingNamespace.ToDisplayString() == StatusNamespace)
                {
                    return true;
                }
            }
            return false;
        }

        private static void Emit(SourceProductionContext spc, StatusModel model)
        {
            if (!model.IsPartial)
            {
                spc.ReportDiagnostic(Diagnostic.Create(NotPartial, model.Location, model.TypeName));
                return;
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable disable");
            sb.AppendLine();
            sb.AppendLine($"using {EntityAddressNamespace};");
            sb.AppendLine($"using {StatusNamespace};");
            sb.AppendLine();

            bool hasNamespace = model.Namespace != null;
            string indent = hasNamespace ? "    " : "";

            if (hasNamespace)
            {
                sb.AppendLine($"namespace {model.Namespace}");
                sb.AppendLine("{");
            }

            sb.AppendLine($"{indent}public partial class {model.TypeName}");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    protected sealed override void AddSignature(EntityAddress address) => address.AddOrSetComponent<StatusSignature<{model.TypeName}>>();");
            sb.AppendLine($"{indent}}}");

            if (hasNamespace)
                sb.AppendLine("}");

            spc.AddSource($"{model.TypeName}.AddSignature.g.cs", sb.ToString());
        }

        private readonly struct StatusModel
        {
            public readonly string Namespace;
            public readonly string TypeName;
            public readonly bool IsPartial;
            public readonly Location Location;

            public StatusModel(string @namespace, string typeName, bool isPartial, Location location)
            {
                Namespace = @namespace;
                TypeName = typeName;
                IsPartial = isPartial;
                Location = location;
            }
        }
    }
}
