// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.ATCGModule.Data
{
    public partial class PlayerCardInDeckInfos
    {
        public string cardID;
        public int quantity;

        [Preserve]
        public PlayerCardInDeckInfos ()
        {
        }
    }
}