// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class BattleSessionModuleBindings
    {
        readonly ICloudCodeService k_Service;
        public BattleSessionModuleBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<string> InitiateSession(string gameModeType, List<ATCGModule.Data.PlayerBattleInfos> playerInfos)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "ATCGModule",
                "InitiateSession",
                new Dictionary<string, object>()
                {
                    {"gameModeType", gameModeType},
                    {"playerInfos", playerInfos},
                });
        }

        public async Task ConnectPlayerToSession(string sessionId)
        {
            await k_Service.CallModuleEndpointAsync(
                "ATCGModule",
                "ConnectPlayerToSession",
                new Dictionary<string, object>()
                {
                    {"sessionId", sessionId},
                });
        }

        public async Task DisconnectPlayerToSession()
        {
            await k_Service.CallModuleEndpointAsync(
                "ATCGModule",
                "DisconnectPlayerToSession",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
